import { Connection, Keypair, PublicKey, Transaction, TransactionInstruction, SystemProgram, sendAndConfirmTransaction } from "@solana/web3.js";
import * as fs from "fs";

const PROGRAM_ID = new PublicKey("h6T7wsEJWMxN2uEZUc4SipEd8Zmz2DWasCDopindjC5");

async function main() {
    console.log("=== Initialize SOL Vault PDA ===\n");

    // Load wallet
    const walletPath = process.env.SOLANA_WALLET || `${process.env.HOME}/.config/solana/id.json`;
    const walletData = JSON.parse(fs.readFileSync(walletPath, "utf-8"));
    const wallet = Keypair.fromSecretKey(new Uint8Array(walletData));
    console.log("Wallet:", wallet.publicKey.toBase58());

    const connection = new Connection("https://api.devnet.solana.com", "confirmed");

    // Derive the SOL vault PDA
    const [solVaultPda, bump] = PublicKey.findProgramAddressSync(
        [Buffer.from("sol_vault")],
        PROGRAM_ID
    );
    console.log("SOL Vault PDA:", solVaultPda.toBase58());
    console.log("Bump:", bump);

    // Check if vault already exists
    const vaultInfo = await connection.getAccountInfo(solVaultPda);
    if (vaultInfo) {
        console.log("\n✅ Vault already exists!");
        console.log("Balance:", vaultInfo.lamports / 1e9, "SOL");
        return;
    }

    // initialize_sol_vault discriminator (generated by Anchor)
    // We'll need to get this from the IDL after build
    // For now, let's fund the PDA directly as a workaround

    console.log("\n Funding vault PDA with 0.1 SOL...");
    const fundTx = new Transaction().add(
        SystemProgram.transfer({
            fromPubkey: wallet.publicKey,
            toPubkey: solVaultPda,
            lamports: 0.1 * 1e9, // 0.1 SOL
        })
    );

    const sig = await sendAndConfirmTransaction(connection, fundTx, [wallet]);
    console.log("✅ Funded vault:", sig);

    const newVaultInfo = await connection.getAccountInfo(solVaultPda);
    console.log("\nVault balance:", newVaultInfo?.lamports ? newVaultInfo.lamports / 1e9 : 0, "SOL");
    console.log("\n=== SOL Vault Ready ===");
}

main().catch(console.error);
